package raf.rs.domaci3.model.enums;

public enum PermissionEnum {
    CAN_CREATE_USER, CAN_READ_USER, CAN_UPDATE_USER, CAN_DELETE_USER,
    CAN_START_MACHINE, CAN_SEARCH_MACHINE, CAN_RESTART_MACHINE, CAN_STOP_MACHINE, CAN_CREATE_MACHINE, CAN_DESTROY_MACHINE,

}
